### ISSUE TITLE
token转账

### ISSUE THREAD

**Issue by yfhuang521** [ethjava/web3j-sample#2]
![_20180523153818](https://user-images.githubusercontent.com/21332031/40410142-8d7e4a1c-5e9f-11e8-9815-9a4f37fd4431.png)

转账的时候报这个错误，能帮忙看看是什么原因吗？

**Comment by TOTOROYang** [comment]
没见过这个错误，你的节点正常么 能通过curl命令去jsonrpc访问不。

**Comment by yfhuang521** [comment]
调用ColdWallet的testTokenTransaction()方法转账，生成了交易但一直是Pending状态，是费用设置有问题吗？
![_20180524103911](https://user-images.githubusercontent.com/21332031/40461604-b6b9dc44-5f3e-11e8-99cc-c4801f7c542b.png)

**Comment by yfhuang521** [comment]
问题解决了,谢谢!
@TOTOROYang

**Comment by yfhuang521** [comment]
@TOTOROYang 
你好，还想请教个问题，通过交易的hash值获取交易详情Transaction对象后，怎么判断这个交易是成功还是失败呢？

**Comment by yfhuang521** [comment]
EthGetTransactionReceipt send = web3j.ethGetTransactionReceipt(txHash).send();  
	        Optional<TransactionReceipt> receiptO = send.getTransactionReceipt();
	        System.out.println(receiptO.isPresent());
	        if (receiptO.isPresent()) {
	        	TransactionReceipt receipt = receiptO.get();
	        	System.out.println(receipt.getStatus());
	        }

**Comment by TOTOROYang** [comment]
@pzhangleo 在参数中没有用到。地址包含在私钥签名后的信息 s r v 中，可以解码得到。

**Comment by TOTOROYang** [comment]
@yfhuang521 在公链中TransactionReceipt 对象里面有status参数可以判断成不成功。0x1成功0x0失败。
私链中可能没有status字段，因为创世块的设置不同。

**Comment by yfhuang521** [comment]
@TOTOROYang
好的，谢谢！

**Comment by pzhangleo** [comment]
多谢解答
