### ISSUE TITLE
idea check out from version control 导入后，无法运行：Error: Could not find or load main class com.ethjava.QuickStart

### ISSUE THREAD

**Issue by zoeleesss** [ethjava/web3j-sample#3]
idea check out from version control 导入后，无法运行：
Error: Could not find or load main class com.ethjava.QuickStart

请问，怎么操作呢？谢谢！

**Comment by TOTOROYang** [comment]
全都是demo代码 在单个文件里运行就行了。 看看maven的两个包下载好了没。
