### ISSUE TITLE
Invalid response received: okhttp3.internal.http.RealResponseBody@72967906

### ISSUE THREAD

**Issue by skyhuihui** [ethjava/web3j-sample#5]
Exception in thread "main" rx.exceptions.OnErrorNotImplementedException: Invalid response received: okhttp3.internal.http.RealResponseBody@72967906
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386)
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.Observable.subscribe(Observable.java:10249)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.Observable.subscribe(Observable.java:10010)
	at com.ethjava.ContractEvent.main(ContractEvent.java:51)

多出出现相同bug，连接的是infura的节点   使用的是at com.ethjava.ContractEvent

**Comment by skyhuihui** [comment]
可联系qq 1414948836

**Comment by TOTOROYang** [comment]
infura 我记得是不开放监听接口的。

**Comment by skyhuihui** [comment]
就是不可以使用 ok http是吧？

**Comment by 401825317** [comment]
@skyhuihui 自己搭建私有链测试，免费的公有链开放rpc权限比较少

**Comment by skyhuihui** [comment]
之前使用admin  创建账户的时候，也是这个问题  好的，我后边自己搭一个节点，parity 和 geth 哪一个好一点

**Comment by TOTOROYang** [comment]
差不多 我自己用的geth。 看评论parity好点。

**Comment by skyhuihui** [comment]
parity有界面体验性好点，但是geth在linux上我用着感觉好点，windows用着感觉不怎么样

**Comment by skyhuihui** [comment]
怎么实现 一笔交易里 多笔转账，可不可以给个类似的 demo，0xbfaaf3381230da0b1fcdbb6216044a66c113a52d2f7993972ce58bd8e8323a6d  类似这种交易的

**Comment by 401825317** [comment]
自己写个智能合约，先研究一下solidaty,你再调你智能合约得这个方法，每笔交易就是你调某个智能合约的某个方法，至于这个方法实现是什么完全在你。

**Comment by TOTOROYang** [comment]
支持

**Comment by skyhuihui** [comment]
可不可以用java实现一个简单的demo参考一下

**Comment by TOTOROYang** [comment]
这是合约功能 跟java没关系

**Comment by Guo1314** [comment]
连接 infura的主网的节点  报异常
**org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: okhttp3.internal.http.RealResponseBody@489115ef**

请问这个问题要怎么样解决？

**Comment by TOTOROYang** [comment]
你去postman试一下 确定你infura的主网节点正常

**Comment by Guo1314** [comment]
@TOTOROYang 我可以 查询代币发行总量、查询代币精度、查询代币符号、查询代币名称   这些都是正常

PersonalUnlockAccount personalUnlockAccount = admin.personalUnlockAccount(fromAddress, password, BigInteger.valueOf(10)).send();     这里就抛异常了，我把代码注释了

**infura转账只能提交 裸交易 请求**

RawTransaction rawTx = RawTransaction.createTransaction(nonce,gasPrice,BigInteger.valueOf(60000),contractAddress,data);
				
Credentials credentials = Credentials.create(privateKey);

byte[] signedMessage = TransactionEncoder.signMessage(rawTx, ChainId.MAINNET,credentials);

String hexValue = Numeric.toHexString(signedMessage);

System.out.println("hexValue--->>"+hexValue);

txHash = web3j.ethSendRawTransaction(hexValue).send().getTransactionHash();

System.out.println("txHash--->>"+txHash);

 **-------------------执行的结果 为空----------------------**

hexValue--->>0xf8a98085012a05f20082ea6094803a6fc118288bfd490f414e8efc857b7c148ea780b844a9059cbb000000000000000000000000703879c98d1d406ba36d53c1a0d0e2aeb4a82130000000000000000000000000000000000000000000000000000000000000000126a01c0c81a9bbe993734ab73daf7e5b592e3c72282bbd618224c001c2f71223bcf0a0029d4bc0f7e3c80cc2e297fc02e83805906db3af437ff0ae2f55b130352985a6

txHash--->>null


**请问大家有遇到这个问题吗？  该如何解决它。**

**Comment by TOTOROYang** [comment]
send的返回打印一下看看报错

**Comment by Guo1314** [comment]
getMessage===insufficient funds for gas * price + value
getData =====null

找到原因了，账户余额不足导致的

**Comment by yfhuang521** [comment]
@skyhuihui 
问题解决了吗?
我用的（https://ropsten.infura.io/SkryPe********）这个节点，也不行，不用本地节点可以吗？
有没有人知道这个问题？
