### ISSUE TITLE
查询代币余额出错

### ISSUE THREAD

**Issue by dazi005** [ethjava/web3j-sample#7]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at com.ethjava.TokenClient.getTokenName(TokenClient.java:119)
	at com.ethjava.TokenClient.main(TokenClient.java:52)

**Comment by wangjunbao2018** [comment]
There’s an error in my private network with error infomations:
16:43:02.857 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"eth_call","params":[{"from":"0x0000000000000000000000000000000000000000","to":"0x952ca071d73cb4ca5a4a68ad8dc9819ddaf68840","data":"0x06fdde03"},"latest"],"id":4}
16:43:02.858 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - --> END POST (188-byte body)
16:43:02.873 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - <-- 200 OK http://localhost:8545/ (15ms)
16:43:02.873 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json
16:43:02.873 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - Vary: Origin
16:43:02.873 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - Date: Sat, 15 Sep 2018 08:43:02 GMT
16:43:02.873 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 39
16:43:02.874 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - 
16:43:02.874 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","id":4,"result":"0x"}

16:43:02.874 [pool-1-thread-1] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (39-byte body)
java.lang.IndexOutOfBoundsException: Index: 0

pls tell me how to solve this problem？ thx

**Comment by TOTOROYang** [comment]
参数不对

**Comment by wangjunbao2018** [comment]
我是几乎拷贝的例子，请问应该传什么参数？thx

**Comment by TOTOROYang** [comment]
data明显不对 没有参数 只有方法名

**Comment by wyh00544** [comment]
我就是demo，也有这样的问题
